[project]
# Whether to enable telemetry (default: true). No personal data is collected.
enable_telemetry = true

# List of environment variables to be provided by each user to use the app.
user_env = []

# Duration (in seconds) during which the session is saved when the connection is lost
session_timeout = 3600

# Enable third parties caching (e.g LangChain cache)
cache = false

# Follow symlink for asset mount (see https://github.com/Chainlit/chainlit/issues/317)
# follow_symlink = false

[features]
# Show the prompt playground
prompt_playground = true

# Process and display HTML in messages. This can be a security risk (see https://stackoverflow.com/questions/19603097/why-is-it-dangerous-to-render-user-generated-html-or-javascript)
unsafe_allow_html = false

# Process and display mathematical expressions. This can clash with "$" characters in messages.
latex = false

# Authorize users to upload files with messages
multi_modal = true

# Allows user to use speech to text
[features.speech_to_text]
    enabled = true
    # See all languages here https://github.com/JamesBrill/react-speech-recognition/blob/HEAD/docs/API.md#language-string
    language = "en-US"

[features.audio]
    min_decibels = -45
    initial_silence_timeout = 3000
    silence_timeout = 1500
    max_duration = 15000
    chunk_duration = 1000
    sample_rate = 44100
[UI]
# Name of the app and chatbot.
name = "SalesBuddy for BetterTech"

# Show the readme while the conversation is empty.
show_readme_as_default = true

# Description of the app and chatbot. This is used for HTML tags.
# description = ""

# Large size content are by default collapsed for a cleaner ui
default_collapse_content = true

# The default value for the expand messages settings.
default_expand_messages = false

# Hide the chain of thought details from the user in the UI.
hide_cot = false

# Link to your github repo. This will add a github button in the UI's header.
# github = ""

# Specify a CSS file that can be used to customize the user interface.
# The CSS file can be served from the public directory or via an external link.
# custom_css = "/public/test.css"
custom_css = "/public/custom_styles.css"
# Override default MUI light theme. (Check theme.ts)
[UI.theme.light]
    background = "#E0F7FA"  # Light Cyan for a refreshing background
    paper = "#FFFFFF"       # Keep the paper white for contrast

    [UI.theme.light.primary]
        main = "#0288D1"     # A vibrant blue as the primary color
        dark = "#01579B"     # A deeper blue for darker elements
        light = "#B3E5FC"    # A light blue for accents and highlights
[UI.theme.dark]
    background = "#1E3A5F"  # A deep, rich blue for the background
    paper = "#2C3E50"       # Slightly lighter for paper elements

    [UI.theme.dark.primary]
        main = "#0288D1"     # Same vibrant blue for consistency
        dark = "#01579B"     # A rich dark blue
        light = "#4FC3F7"    # A lighter blue for accents
        
[meta]
generated_by = "0.7.700"
